AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/omniauth/strategies/tinkoff_id_spec.rb

Naming/FileName:
  Exclude:
    - lib/omniauth-tinkoff-id.rb

Gemspec/RequireMFA:
  Enabled: false
